# Generated by Django 2.2.2 on 2019-06-25 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('build_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_stage', models.CharField(max_length=200)),
                ('i_completed', models.BooleanField(default=False)),
                ('b_completed', models.BooleanField(default=False)),
                ('s_completed', models.BooleanField(default=False)),
                ('c_completed', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('M1_ip', models.CharField(max_length=15)),
                ('M2_ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('hcsec_name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_result_loc', models.CharField(max_length=300)),
                ('b_result_loc', models.CharField(max_length=300)),
                ('s_result_loc', models.CharField(max_length=300)),
                ('proxy_loc1', models.CharField(max_length=300)),
                ('proxy_loc2', models.CharField(max_length=300)),
                ('plugin_loc1', models.CharField(max_length=300)),
                ('plugin_loc2', models.CharField(max_length=300)),
                ('build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Build')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
